In [2]:
import numpy as np

matrix = np.array([[1, 2], [3, 4]])
print(matrix)
print(matrix.transpose())

[[1 2]
 [3 4]]
[[1 3]
 [2 4]]


In [5]:
np.random.rand(3,3)

array([[0.93793135, 0.446442  , 0.54388726],
       [0.18855993, 0.75271571, 0.35520231],
       [0.43047152, 0.48833282, 0.37189156]])

In [ ]:
squares = [i**2 for i in range(1, 11)]
print(squares)

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]


In [ ]:
divisible_by = 4
filtered_squares = [x for x in squares if x % divisible_by == 0]
print(filtered_squares)